{ pkgs, inputs, ... }:

with pkgs;
[
  tor-browser
  brave
  inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
  signal-desktop
  telegram-desktop
  slack
  nextcloud-client
  virt-manager
  papirus-icon-theme
  popsicle
  cloudflared
  prismlauncher
  lshw-gui
  parted
  gptfdisk
  cpupower-gui
  jre8
  gvfs
  nemo
  nautilus
  mission-center
  resources
  gnome-2048
  gnome-calculator
  gparted
  gnome-disk-utility
  papers
  snapshot
  zathura
  bluetuith
  libnotify
  kdePackages.qt6ct
  libsForQt5.qt5ct
  kdePackages.qtwayland
  libsForQt5.qtwayland
  kdePackages.qtstyleplugin-kvantum
  libsForQt5.qtstyleplugin-kvantum
]
