# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-33a241fd-d641-4fff-aeb2-ede1cd20b72d";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  boot.initrd.luks.devices."luks-33a241fd-d641-4fff-aeb2-ede1cd20b72d".device =
    "/dev/disk/by-uuid/33a241fd-d641-4fff-aeb2-ede1cd20b72d";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-33a241fd-d641-4fff-aeb2-ede1cd20b72d";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BC87-A4FD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/dc8596a2-789f-44b0-ad5f-dd9643cd6a56"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
